[env]
framework = arduino
monitor_speed = 115200

; Use the modern pioarduino framework fork to bring in full Core v3.0+ support (Required for C6)
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

; Evaluate dependencies aggressively
lib_ldf_mode = deep
lib_compat_mode = strict

; Force-inject HTTPClient and WiFiClientSecure into the build path mapping
lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.4
    gilmaimon/ArduinoWebsockets @ ^0.5.3
    adafruit/RTClib @ ^2.1.4
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.16.1
    Update
    HTTPClient
    WiFiClientSecure
    SPI
    Wire
    SD

; Block legacy debris from your global cache folders
lib_ignore =
    WiFi101
    WiFi101_Generic
    WiFiEspAT
    WiFiNINA_Generic
    DueFlashStorage
    EthernetWebServer
    SinricPro_Generic
    EthernetENC
    WiFiWebServer


[env:waveshare_s3_geek]
; Override core settings to allocate full 16MB flash maps on both boards and custom partitions.csv in the root folder
board_build.partitions = partitions-16M.csv
board_upload.flash_size = 16MB
board_build.flash_size = 16MB

board = esp32-s3-devkitc-1
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1  ; Required for S3 (Native USB OTG)
    -D CORE_DEBUG_LEVEL=1
    

[env:waveshare_c6_geek]
; Override core settings to allocate full 16MB flash maps on both boards and custom partitions.csv in the root folder
board_build.partitions = partitions-16M.csv
board_upload.flash_size = 16MB
board_build.flash_size = 16MB

board = esp32-c6-devkitc-1 
build_flags = 
    -D ARDUINO_USB_MODE=1          ; <--- Force JTAG to act as a CDC interface
    -D ARDUINO_USB_CDC_ON_BOOT=1   ; <--- Instantiate the CDC object at boot
    -D CORE_DEBUG_LEVEL=1

[env:waveshare_c6_geek-dev]
; Override core settings to allocate full 16MB flash maps on both boards and custom partitions.csv in the root folder
board_build.partitions = partitions-8M.csv
board_upload.flash_size = 8MB
board_build.flash_size = 8MB

board = esp32-c6-devkitc-1 
build_flags = 
    -D ARDUINO_USB_MODE=1          ; <--- Force JTAG to act as a CDC interface
    -D ARDUINO_USB_CDC_ON_BOOT=1   ; <--- Instantiate the CDC object at boot
    -D CORE_DEBUG_LEVEL=1